// Ascidoc Cheat Sheet: https://github.com/powerman/asciidoc-cheatsheet

:doctitle: Linked Data Store

ifndef::env-github[]
:doctype: book
:page-layout: docs
:numbered:
:toc: left
:toclevels: 3
:factory-ref: https://github.com/asciidoctor/asciidoctor-stylesheet-factory
:uri-svgo: https://github.com/svg/svgo
//:source-highlighter: highlightjs
:source-highlighter: coderay
:coderay-linenums-mode: inline
:coderay-css: class
:icons: font
endif::[]

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:toc-placement: preamble
endif::[]

[NOTE]
====
This documentation is work in progress!
====

Linked Data Store (LDS) offers a well defined resource-oriented RESTful API over a runtime configured information model allowing users to read and write data. LDS supports _time-based-data-versioning_ capabilities that allows it to act as an immutable datastore where data can be read as they were back in time.

The information model configuration is represented using JSON Schema and LDS will interpret schema properties prefixed with `_link_property_` as directives to describe relationships between entities in the information model.

LDS is intended to be a smart service layer between information-model-aware applications and the underlying persistence-technology (e.g. Postgres, Neo4j, FoundationDb, BigTable).


ifdef::env-github[]
= Table of Contents

. link:docs/background.adoc[Background]
. link:docs/architecture.adoc[Architecture]
. link:docs/administration.adoc[Administration]
. link:docs/examples.adoc[Examples]
endif::[]

ifndef::env-github[]
:leveloffset: +1
include::docs/background.adoc[]
include::docs/architecture.adoc[]
include::docs/administration.adoc[]
include::docs/examples.adoc[]
:leveloffset: -1
endif::[]

== Other references

* https://json-schema.org/[IETF JSON Schema]
* https://www.ietf.org/archive/id/draft-zyp-json-schema-04.txt[JSON Schema Draft 4]

== License

This software is licensed under link:LICENSE[APL 2.0]
