= Administration

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:toc-placement: preamble
endif::[]


== Pre-requisites

* JSON Schemas must be defined before the server can start
* Persistence Providers has their own bespoke configurations. Please refer to specific providers for configuration

[WARNING]
====
Memory provider should only used for testing purposes
====


== Schema

LDS uses JSON Schema draft04. The schemas defines the data model and uses _directives_ to express links between json resources. Further during startup the schemas configures all REST APIs.

=== Directives

The (_linked_property_(resource)) directive defines how two data entities are connected. This allows you connect data from one property to another.

== Configuration

The persistence providers share a common configuration declared in the `linked-data-store-core/src/main/resources/application-defaults.properties` and specifc configurations are located in each _Docker Provider_.

.Configuration properties
|===
|Key |Value |Description

|http.host
|0.0.0.0
|Binds default loopback and private IP

|http.cors.allow.origin
|*
|Constrain what hosts should have access to the web server

|namespace.default
|ns
|Default URI namespace prefix

|specification.schema
|(empty)
|Location of where LDS reads its schemas. Inside docker images the default is /schema

|===



=== Memory Persistence Provider

(Work in Progress)

=== Neo4j Persistence Provider

(Work in Progress)

=== PostgreSQL Persistence Provider

(Work in Progress)

=== FoundationDb Persistence Provider

(Work in Progress)

